### ISSUE TITLE
V3.0 release checklist

### ISSUE THREAD

**Issue by general-ronimus** [general-ronimus/vwars#35]
- [x] game re-balancing: https://github.com/general-ronimus/vwars/issues/34
- [X] implement stats and leaderboard uplift
- [x] implement war delete
- [x] consider transactions for war conclude (no longer MVP, create new ticket)
- [x] tidy up vwa command responses
- [x] hall per user command
- [x] finalize hall command
- [x] test rebalance changes
- [x] re-test stealth in dev
- [x] re-test vwa commands in dev
- [x] copy v2.0 war data to dev server and test conclusion in dev
- [x] fix the task master token loading issue
- [x] staging deploy!
- [x] copy v2.0 war to staging environment and activate
- [x] test stealth in staging
- [x] test vwa commands in staging
- [x] test conclusion in staging
- [x] create closed alpha test war in FW
- [x] re-test everything
- [x] cut beta release
- [x] create open beta test war in FW
- [x] open up beta testing
- [x] ticket any bugs or issues
- [x] address critical bugs
- [x] cut v3.0 release
