### ISSUE TITLE
V4.0 release roadmap

### ISSUE THREAD

**Issue by general-ronimus** [general-ronimus/vwars#56]
- [ ] finalize v4 game manifest
- [ ] introduce v coins (depends on finalizing currency system in the manifest)
- [ ] off-season mining
- [ ] automatic war initialization
- [ ] alliances (expanded gifting, friendly-fire prevention)
- [ ] war brackets
- [ ] variable damage
- [ ] initial structures
